spring.application.name=javabank-backend

server.port=${PORT:5000}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app.jwt.secret=${JWT_SEC:change-me-in-env}
app.jwt.expiration-ms=43200000
app.analytics.ingestion-url=${INGESTION_API_URL:http://localhost:8000/events}

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:3002},http://localhost:3000,http://localhost:3001,http://localhost:3002
