services:
  # JavaBank Backend (Spring Boot)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: javabank-backend
    environment:
      DB_URL: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
      DB_URL_SESSION_POOLER: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
      DB_USERNAME: postgres.vveddtextpaviyunihwh
      DB_PASSWORD: abhishekkumawat
      JWT_SEC: javabank_super_secure_jwt_secret_key_256_bits_minimum_2026
      PORT: 5001
      FRONTEND_URL: http://localhost:3000
      INGESTION_API_URL: http://host.docker.internal:8000/events
      ANALYTICS_API_URL: http://host.docker.internal:8001
    ports:
      - "5001:5001"
    networks:
      - javabank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # JavaBank Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: javabank-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5001/api
      NEXT_PUBLIC_INGESTION_URL: http://localhost:8000/events
    ports:
      - "3000:3000"
    networks:
      - javabank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  javabank-network:
    driver: bridge
